kind: pipeline
type: docker
name: website

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    volumes:
    - name: docker_sock
      path: /var/run/docker.sock
    settings:
      repo: registry.rpanic.com/rpanic/pool-backend
      registry: registry.rpanic.com
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: ironfish-cli/Dockerfile

image_pull_secrets:
  - repo_login
  
volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
  branch:
    - rpanic/miningpool-v2-backend